CUDA_VISIBLE_DEVICES=0 python medical_search_gpt/stages/dpo_training_simple.py \
    --model_name_or_path outputs-sft-qwen3.5-0.8b-merged \
    --train_file_dir ./data/reward \
    --max_train_samples 50 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --max_steps 30 \
    --learning_rate 5e-5 \
    --beta 0.1 \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --max_source_length 256 \
    --max_target_length 128 \
    --save_steps 30 \
    --logging_steps 5 \
    --bf16 True \
    --gradient_checkpointing True \
    --output_dir outputs-dpo-qwen3.5-0.8b-v1
